version: "3.9"
services:
  api:
    build:
      context: ..
      dockerfile: infra/Dockerfile.api
    env_file: ../.env
    ports: ["8000:8000"]
    depends_on: [redis]

  worker:
    build:
      context: ..
      dockerfile: infra/Dockerfile.worker
    env_file: ../.env
    depends_on: [redis]

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
